apiVersion: metallb.io/v1beta1
kind: MetalLB
metadata:
  name: metallb
  namespace: metallb-system
spec:
  nodeSelector:  
    node-role.kubernetes.io/infra: ""
  speakerTolerations:   
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoExecute"
  - key: "node-role.kubernetes.io/infra"
    operator: "Exists"
    effect: "NoSchedule"